backend:
  name: github
  repo: YOUR_USERNAME/YOUR_REPOSITORY_NAME # Replace with your GitHub username and repository name
  branch: main # Or your default branch
  # For private repositories, or to support editorial workflow,
  # you'll need to enable GitHub authentication.
  # See: https://decapcms.org/docs/authentication-backends/#github-backend

# Optional: Enable Netlify Identity for GitHub authentication (recommended for private repos)
# publish_mode: editorial_workflow # Enable drafts, reviews, and publishing control

media_folder: "static/images/uploads" # Location where uploaded media files will be stored
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with this path

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the CMS UI
    folder: "_posts/blog" # The path to the folder where blog posts are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", optional: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}